# Generated by Django 4.1.5 on 2023-01-15 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mediafile.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name='uuid',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='created date-time'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='updated date-time'
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name='deleted date-time',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        blank=True, default='', max_length=32, verbose_name='title'
                    ),
                ),
                (
                    'external_url',
                    models.URLField(
                        blank=True, default='', verbose_name='external url'
                    ),
                ),
                (
                    'file_location',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=128,
                        verbose_name='file location',
                    ),
                ),
                (
                    'file_name',
                    models.CharField(
                        blank=True, default='', max_length=64, verbose_name='file name'
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        default='',
                        upload_to=mediafile.models.MediaFile.get_upload_to,
                        verbose_name='file',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='owner',
                    ),
                ),
            ],
            options={
                'verbose_name': 'media file',
                'verbose_name_plural': 'media file',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='mediafile',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ('external_url', ''), models.Q(('file', ''), _negated=True)
                    ),
                    models.Q(
                        models.Q(('external_url', ''), _negated=True), ('file', '')
                    ),
                    _connector='OR',
                ),
                name='not_both_external_url_and_file_blank',
            ),
        ),
    ]
